<?php

/**
 * Implementation of hook_views_api().
 */
function views_tree_views_api() {
  return array(
    'api' => 2,
    'path' => drupal_get_path('module', 'views_tree'),
  );
}

function views_tree_theme($existing, $type, $theme, $path) {
  return array(
    'views_tree_inner' => array(
      'arguments' => array(
        'view' => NULL,
        'options' => array(),
        'rows' => array(),
        'title' => NULL,
        'result' => array(),
        'parent' => NULL,
      ),
      'file' => 'views_tree.theme.inc',
    ),
  );
}

