<?php 
/**
 * views template to output one 'row' of a view.
 * This code was generated by the views theming wizard
 * Date: 27 February 2007 - 10:55pm
 * View: og_notes
 *
 * Variables available:
 * $view -- the entire view object. Important parts of this object are
 *   og_notes, .
 * $view_type -- The type of the view. Probably 'page' or 'block' but could
 *   also be 'embed' or other string passed in from a custom view creator.
 * $node -- the raw data. This is not a real node object, but will contain
 *   the nid as well as other support fields that might be necessary.
 * $count -- the current row in the view (not TOTAL but for this page) starting
 *   from 0.
 * $stripe -- 'odd' or 'even', alternating. * $title -- Display the title of the node.
 * $title_label -- The assigned label for $title
 * $created -- Display the post time of the node.
 * $created_label -- The assigned label for $created
 * $field_character_name_value -- 
 * $field_character_name_value_label -- The assigned label for $field_character_name_value
 * $field_parent_note_nid -- 
 * $field_parent_note_nid_label -- The assigned label for $field_parent_note_nid
 * $name -- This will display all taxonomy terms associated with the node that are members of <em>Location</em>. Note that this causes one extra query per row displayed, and might have a minor performance impact.
 * $name_label -- The assigned label for $name
 * $nid -- Display the NID of a node.
 * $nid_label -- The assigned label for $nid
 *
 * This function goes in your views-list-og_notes.tpl.php file
 */
 
 //now we add the stylesheet...
  //drupal_add_css(path_to_theme() .'/views-list-og_notes.css');
  
  ?>
<div class="view-field view-data-title">
  <?php print $title?>
</div>

<div class="view-field view-data-created">
  <?php print $created?>
</div>

<div class="view-field view-data-field-character-name-value">
  <?php print $field_character_name_value?>
</div>

<div class="view-field view-data-name">
  <?php print $name?>
</div>

